-- ============================================
-- Script de inserción a la base de datos de revistas
-- ============================================

USE revistas;

-- --------------------------------------------
-- 1. Indexaciones
-- --------------------------------------------
INSERT INTO indexaciones (indexacion) VALUES
    ('CINAHL'),
    ('Catálogos académicos'),
    ('Catálogos institucionales'),
    ('Catálogos regionales'),
    ('Catálogos universitarios'),
    ('Cochrane'),
    ('Conahcyt'),
    ('DOAJ'),
    ('Dialnet'),
    ('Directorios académicos'),
    ('EMBASE'),
    ('ESCI'),
    ('Elsevier'),
    ('Google Scholar'),
    ('IMBIOMED'),
    ('Index Medicus'),
    ('Latindex'),
    ('Lilacs'),
    ('MEDLINE'),
    ('MIAR'),
    ('Medigraphic'),
    ('Portal institucional universitario'),
    ('PsycINFO'),
    ('PubMed'),
    ('PubMed Central'),
    ('PubMed/MEDLINE'),
    ('Redalyc'),
    ('SCIE'),
    ('SCImago'),
    ('SciELO'),
    ('SciELO México'),
    ('ScienceDirect'),
    ('Scopus'),
    ('Web of Science');

-- --------------------------------------------
-- 2. Revistas
-- --------------------------------------------
INSERT INTO revistas
    (titulo_revista, tema, cuartil, idioma, costo, puntuacion, nivel_recomendacion, descripcion, enlace)
VALUES
    ('Salud Publica de México', 'Salud', 'Q2', 'Español', 0.00, 5, 3, 'Una de las revistas de salud pública más importantes de México y Latinoamérica. Fundada en 1959, pública investigación sobre problemas de salud de la población con enfoque interdisciplinario. Arbitraje doble ciego.', 'https://saludpublica.mx'),
    ('Boletín Medico del Hospital Infantil de México', 'Salud', 'Q3', 'Español', 0.00, 5, 5, 'publicación oficial del Hospital Infantil de México Federico Gómez. Una de las revistas médicas más antiguas del país. Cubre investigación clínica y básica en pediatría nacional.', 'https://www.bmhim.com'),
    ('Cirugía y Cirujanos', 'Salud', 'Q3', 'Español', 0.00, 5, 3, 'Órgano oficial de la Academia Mexicana de Cirugía, asesor del Gobierno Federal en materia de salud. Fundada en 1933. Publica en formato bilingüe.', 'https://cirugiaycirujanos.com'),
    ('Gaceta Médica de México', 'Salud', 'Q3', 'Español', 0.00, 5, 3, 'Una de las publicaciones médicas más antiguas de México, fundada en 1864. Cubre investigación clínica, biomédica y de salud pública. Arbitraje doble ciego.', 'https://www.anmm.org.mx/gaceta'),
    ('Salud Mental', 'Salud', 'Q3', 'Español', 0.00, 5, 3, 'publicación oficial del Instituto Nacional de Psiquiatría. Es la única revista mexicana de psiquiatría indexada en Web of Science y Scopus.', 'https://www.revistasaludmental.mx'),
    ('Archivos de Cardiología de Mexico', 'Salud', 'Q3', 'Español', 0.00, 5, 3, 'Órgano oficial de la Sociedad Mexicana de Cardiología. Cubre todas las áreas de la cardiología clínica, intervencionista y básica.', 'https://www.archivoscardiologia.com'),
    ('Revista de la Facultad de Medicina UNAM', 'Salud', 'SIN ASIGNAR', 'Español', 0.00, 4, 5, 'publicación universitaria de la Facultad de Medicina de la UNAM. Enfocada en la difusión del conocimiento médico con perspectiva educativa.', 'https://www.revistas.unam.mx/index.php/rfm'),
    ('Acta Pediátrica de Mexico', 'Salud', 'SIN ASIGNAR', 'Español', 0.00, 4, 5, 'Publicación oficial del Instituto Nacional de Pediatria de Mexico. Buena puerta de entrada para publicar en el área médica nacional.', 'https://www.actapediatrica.org.mx'),
    ('Revista Mexicana de Medicina Familiar', 'Salud', 'SIN ASIGNAR', 'Español', 0.00, 3, 5, 'Revista especializada en medicina de primer nivel de atención. En proceso de Indexación en SciELO, lo que ampliará su visibilidad.', 'https://www.medigraphic.com/rmmf'),
    ('Revista Mexicana de Neurociencia', 'Salud', 'SIN ASIGNAR', 'Español', 0.00, 3, 5, 'Órgano oficial de la Academia Mexicana de Neurología. Publica investigación en neurociencias básicas y clínicas.', 'https://revmexneuroci.com'),
    ('Revista Mexicana de Urología', 'Salud', 'SIN ASIGNAR', 'Español', 0.00, 3, 3, 'Órgano oficial de la Sociedad Mexicana de Urología. Cubre urología clínica, oncológica e intervencionista.', 'https://www.revistamexicanadeurologia.com'),
    ('Revista de Medicina e Investigación UAEM', 'Salud', 'SIN ASIGNAR', 'Español', 0.00, 3, 5, 'Revista universitaria de la UAEM distribuida por Elsevier. Sin costo alguno. Ideal como primera publicación para estudiantes y docentes que inician en investigación.', 'https://www.elsevier.es/es-revista-revista-medicina-e-investigacion-353'),
    ('Revista Panamericana de Salud Publica (OPS/PAHO)', 'Salud', 'Q2', 'Otro', 0.00, 5, 3, 'La publicación científica más importante de la OPS. Referente en salud pública latinoamericana. Cuádruple revisión de idiomas. Muy alta visibilidad internacional.', 'https://journal.paho.org/es'),
    ('Cadernos de Saude Publica (Brasil)', 'Salud', 'Q1', 'Otro', 0.00, 5, 3, 'Una de las revistas de salud pública más citadas de Latinoamérica. Q1 en Scopus. Publicada por FIOCRUZ. Arbitraje doble ciego.', 'https://www.scielo.br/csp'),
    ('Ciencia & Saude Coletiva (Brasil)', 'Salud', 'Q1', 'Otro', 0.00, 5, 3, 'Q1 en Scopus sin APC. Muy activa en temas de inequidad en salud, políticas públicas y determinantes sociales. Publica números temáticos de gran difusión regional.', 'https://www.cienciaesaudecoletiva.com.br'),
    ('Revista de Saude Publica (Brasil)', 'Salud', 'Q2', 'Otro', 0.00, 5, 3, 'Una de las revistas más antiguas de Brasil en salud pública. Fundada en 1967. Cubre epidemiología, salud ambiental, ocupacional y política sanitaria.', 'https://www.scielo.br/rsp'),
    ('Biomedica (Colombia)', 'Salud', 'Q3', 'Español', 0.00, 5, 5, 'Publicación oficial del Instituto Nacional de Salud de Colombia. Enfasis en enfermedades tropicales, virología y salud pública latinoamericana.', 'https://revistabiomedica.org'),
    ('Revista de Ciencias de la Salud (Universidad del Rosario)', 'Salud', 'Q3', 'Español', 0.00, 5, 5, 'Revista universitaria con buena Indexación para su tipo. Sin APC. Cubre todas las áreas de las ciencias de la salud con enfoque multidisciplinario.', 'https://revistas.urosario.edu.co/index.php/revsalud'),
    ('Investigación y Educacion en Enfermeria', 'Salud', 'Q3', 'Otro', 0.00, 5, 5, 'Una de las revistas de enfermería mejor indexadas de Latinoamérica. Acepta artículos en tres idiomas.', 'https://revistas.udea.edu.co/index.php/iee'),
    ('Ciencia & Enfermeria', 'Salud', 'Q3', 'Español', 0.00, 5, 5, 'Primera revista de enfermería chilena en ingresar a Web of Science y Scopus. Referente regional para la disciplina.', 'https://www.scielo.cl/scielo.php?pid=0717-9553&script=sci_serial'),
    ('Epidemiologia e Servicios de Saude (Brasil)', 'Salud', 'Q2', 'Otro', 0.00, 5, 5, 'Destaca por traducir todos los artículos al inglés de forma gratuita. Sin costo alguno para autores ni lectores.', 'https://www.saude.gov.br/ess'),
    ('Acta Medica Colombiana', 'Salud', 'SIN ASIGNAR', 'Español', 0.00, 4, 5, 'Revista colombiana sin APC. Indexada en Latindex y DOAJ. Buena opción para investigadores hispanohablantes que inician.', 'https://www.actamedicacolombiana.com'),
    ('Revista Colombiana de Obstetricia y Ginecologia', 'Salud', 'Q4', 'Español', 0.00, 5, 5, 'Revista de referencia en gineco-obstetricia latinoamericana. Sin costo. Acepta guias de practica clínica y consensos.', 'https://revista.fecolsog.org'),
    ('Medicina (Buenos Aires)', 'Salud', 'Q4', 'Español', 0.00, 5, 5, 'Una de las revistas médicas más antiguas de Argentina, fundada en 1939. Indexada en PubMed y Scopus.', 'https://www.medicinabuenosaires.com'),
    ('Revista Medica de Chile', 'Salud', 'Q3', 'Español', 0.00, 5, 3, 'Fundada en 1872, es una de las revistas médicas más antiguas de Latinoamérica. Indexada en PubMed, Scopus y WoS.', 'https://www.revistamedicadechile.cl'),
    ('The Lancet', 'Salud', 'Q1', 'Inglés', 0.00, 5, 1, 'Revista médica de referencia internacional con los más altos estandares de revisión. Fundada en 1823.', 'https://www.thelancet.com'),
    ('BMJ (British Medical Journal)', 'Salud', 'Q1', 'Inglés', 4500.00, 5, 1, 'Segunda revista médica general más importante del mundo. Fundada en 1840. Alta visibilidad global.', 'https://www.bmj.com'),
    ('JAMA (Journal of the American Medical Association)', 'Salud', 'Q1', 'Inglés', 3000.00, 5, 1, 'Una de las tres grandes revistas médicas mundiales. Fundada en 1883. Requiere registro de ensayos clínicos previo a publicación.', 'https://jamanetwork.com/journals/jama'),
    ('New England Journal of Medicine (NEJM)', 'Salud', 'Q1', 'Inglés', 6000.00, 5, 1, 'La revista con mayor factor de impacto en medicina. Fundada en 1812. Representa el tope de la publicación médica internacional.', 'https://www.nejm.org'),
    ('PLOS Medicine', 'Salud', 'Q1', 'Inglés', 3500.00, 5, 3, '100% open access. Publicada por PLOS, editorial sin fines de lucro. Evalua la solidez metodologica del artículo, no su potencial impacto.', 'https://journals.plos.org/plosmedicine'),
    ('PLOS ONE', 'Salud', 'Q2', 'Inglés', 1895.00, 5, 3, 'La revista con mayor número de artículos publicados en el mundo. Evalua validez científica, no potencial impacto. Waivers disponibles para Mexico.', 'https://journals.plos.org/plosone'),
    ('BMC Public Health', 'Salud', 'Q1', 'Inglés', 2790.00, 5, 3, 'Parte de la familia BioMed Central de Springer Nature. Q1 en Scopus. Activa en determinantes sociales de salud y epidemiología comunitaria.', 'https://bmcpublichealth.biomedcentral.com'),
    ('BMC Medicine', 'Salud', 'Q1', 'Inglés', 3290.00, 5, 1, 'Revista flagship de BioMed Central. Alto factor de impacto. Enfocada en investigación translacional de relevancia clínica directa.', 'https://bmcmedicine.biomedcentral.com'),
    ('Journal of Global Health', 'Salud', 'Q1', 'Inglés', 0.00, 5, 3, 'Revista Q1 sin APC, caso poco común. Excelente para investigación sobre desigualdades globales en salud y salud materno-infantil.', 'https://jogh.org'),
    ('Global Health: Science and Practice', 'Salud', 'Q2', 'Inglés', 0.00, 5, 3, 'Ideal para investigación operacional y de implementación en salud global. Sin APC. Acepta lecciones aprendidas, formato que facilita publicar experiencias de campo.', 'https://www.ghspjournal.org'),
    ('Bulletin of the World Health Organization (OMS)', 'Salud', 'Q1', 'Inglés', 0.00, 5, 3, 'Publicación oficial de la OMS. Q1 sin APC. Prioriza investigación de paises en desarrollo. Resumenes en seis idiomas.', 'https://www.who.int/bulletin'),
    ('Frontiers in Public Health', 'Salud', 'Q2', 'Inglés', 1300.00, 5, 3, 'Modelo de revisión abierta donde los revisores son identificados. Proceso editorial rápido. Popular entre investigadores de Latinoamérica.', 'https://www.frontiersin.org/journals/public-health'),
    ('Frontiers in Medicine', 'Salud', 'Q2', 'Inglés', 2950.00, 5, 2, 'Q2 con tasa de aceptacion relativamente alta. Evalua validez científica, no impacto esperado. Cubre un amplio espectro de medicina clínica.', 'https://www.frontiersin.org/journals/medicine'),
    ('International Journal of Environmental Research and Public Health (IJERPH)', 'Salud', 'Q2', 'Inglés', 3600.00, 5, 3, 'Una de las revistas MDPI más activas. Proceso editorial ágil. Cubre salud ambiental, ocupacional y comunitaria.', 'https://www.mdpi.com/journal/ijerph'),
    ('Nutrients', 'Salud', 'Q1', 'Inglés', 3600.00, 5, 2, 'Revista Q1 especializada en nutrición. Alta demanda para estudios dietéticos, nutraceuticos y epidemiología nutricional.', 'https://www.mdpi.com/journal/nutrients'),
    ('International Journal of Clinical and Health Psychology', 'Salud', 'Q1', 'Otro', 0.00, 5, 5, 'Caso excepcional: Q1 en Scopus y WoS sin ninguna APC. Acepta en español. Ideal para investigación en psicología de la salud y salud mental de autores hispanohablantes.', 'https://www.ijchp.net'),
    ('Journal of Epidemiology and Community Health', 'Salud', 'Q1', 'Inglés', 3750.00, 5, 1, 'Revista BMJ especializada en epidemiología social. Cubre determinantes sociales, desigualdades en salud y salud urbana.', 'https://jech.bmj.com'),
    ('American Journal of Public Health (AJPH)', 'Salud', 'Q1', 'Inglés', 3100.00, 5, 2, 'Referente en salud pública desde 1911. Publicación oficial de la APHA. Muy influyente en política de salud.', 'https://ajph.aphapublications.org'),
    ('Social Science & Medicine', 'Salud', 'Q1', 'Inglés', 3450.00, 5, 3, 'Referente en ciencias sociales aplicadas a la salud. Acepta metodología cualitativa, cuantitativa y mixta. Muy citada en salud pública.', 'https://www.journals.elsevier.com/social-science-and-medicine'),
    ('Health Policy and Planning', 'Salud', 'Q1', 'Inglés', 2800.00, 5, 3, 'Especializada en investigación de sistemas y políticas sanitarias. Publicada por Oxford. Relevante para estudios sobre política de salud latinoamericana.', 'https://academic.oup.com/heapol'),
    ('Tropical Medicine & International Health', 'Salud', 'Q2', 'Inglés', 4400.00, 5, 1, 'Ideal para enfermedades tropicales como dengue, malaria y parasitosis. Relevante para investigación en regiones tropicales de Mexico.', 'https://onlinelibrary.wiley.com/journal/13653156'),
    ('Journal of Infectious Diseases', 'Salud', 'Q1', 'Inglés', 3500.00, 5, 1, 'Publicación oficial de la IDSA. Referente en virología, bacteriología e inmunología infecciosa.', 'https://academic.oup.com/jid'),
    ('Revista Española de Salud Publica', 'Salud', 'Q3', 'Español', 0.00, 5, 5, 'Gratuita e indexada en PubMed. Buena opción para autores hispanohablantes sin costo de publicación.', 'https://scielo.isciii.es/scielo.php?pid=1135-5727&script=sci_serial'),
    ('Gaceta Sanitaria', 'Salud', 'Q2', 'Español', 0.00, 5, 5, 'Revista Q2 en español sin APC, indexada en PubMed y WoS. Muy recomendada para investigadores de Latinoamérica.', 'https://www.gacetasanitaria.org'),
    ('Atencion Primaria', 'Salud', 'Q3', 'Español', 0.00, 5, 5, 'Referente en medicina familiar hispanohablante. Sin APC e indexada en PubMed. Acepta investigación en primer nivel de atención con relevancia latinoamericana.', 'https://www.elsevier.es/es-revista-atencion-primaria-27'),
    ('Journal of Health, Population and Nutrition', 'Salud', 'Q2', 'Inglés', 0.00, 5, 3, 'Q2 sin APC. Parte de BioMed Central/Springer Nature. Enfocada en nutrición comunitaria y salud en paises en desarrollo.', 'https://jhpn.biomedcentral.com'),
    ('Scientific Reports', 'Multidisciplinaria', 'Q1', 'Inglés', 2500.00, 4, 5, 'Revista multidisciplinaria de acceso abierto de Nature Portfolio, centrada en ciencias naturales. wikipedia+3', 'https://www.nature.com/srep/'),
    ('Heliyon', 'Multidisciplinaria', 'Q2', 'Inglés', 2160.00, 4, 4, 'Revista multidisciplinaria de acceso abierto de Elsevier.', 'https://www.heliyon.com/'),
    ('Frontiers in Science', 'Multidisciplinaria', 'Q2', 'Inglés', 3250.00, 3, 3, 'Revista de Frontiers enfocada en investigación científica.', 'https://www.frontiersin.org/journals/science'),
    ('Journal of Multidisciplinary Studies', 'Multidisciplinaria', 'SIN ASIGNAR', 'Inglés', 30.00, 2, 1, 'Revista multidisciplinaria enfocada en diversas áreas del conocimiento.', 'https://www.jmds.org/'),
    ('BMJ Open', 'Multidisciplinaria', 'Q1', 'Inglés', 2900.00, 4, 4, 'Revista de acceso abierto con revisión por pares y cobertura biomédica amplia. wikipedia+3', 'https://bmjopen.bmj.com/'),
    ('Nature Communications', 'Multidisciplinaria', 'Q1', 'Inglés', 6290.00, 5, 5, 'Revista de acceso abierto de alto impacto de Nature. nature+2', 'https://www.nature.com/ncomms'),
    ('Science Advances', 'Multidisciplinaria', 'Q1', 'Inglés', 5450.00, 5, 5, 'Revista multidisciplinaria abierta de AAAS. scholar9+1', 'https://www.science.org/doi/journal/sadv'),
    ('PLOS Biology', 'Multidisciplinaria', 'Q1', 'Inglés', 5500.00, 4, 3, 'Revista de alto impacto en ciencias biológicas.', 'https://journals.plos.org/plosbiology'),
    ('eLife', 'Multidisciplinaria', 'SIN ASIGNAR', 'Inglés', 2500.00, 4, 3, 'Revista científica de biología y medicina.', 'https://elifesciences.org/'),
    ('Revista Colombiana de Ciencias Multidisciplinarias', 'Multidisciplinaria', 'Q3', 'Español', 0.00, 2, 1, 'Revista académica de la Universidad Nacional de Colombia. biblioteca.uniandes.edu', 'https://revistas.unal.edu.co/index.php/multidisciplinarias'),
    ('Ciencia y Multidisciplinariedad', 'Multidisciplinaria', 'Q2', 'Español', 0.00, 2, 2, 'Revista universitaria enfocada en temas multidisciplinarios. biblioteca.uniandes.edu', 'https://revistas.udantioquia.edu.co/ciencia-multidisciplinariedad'),
    ('Revista Multidisciplinar Latinoamericana', 'Multidisciplinaria', 'Q3', 'Español', 0.00, 2, 1, 'Revista latinoamericana de enfoque multidisciplinario. biblioteca.uniandes.edu', 'https://revistas.univalle.edu.co/multidisciplinar'),
    ('Investigaciones Multidisciplinarias', 'Multidisciplinaria', 'Q2', 'Español', 0.00, 2, 1, 'Revista institucional orientada a investigación multidisciplinaria. biblioteca.uniandes.edu', 'https://revistas.ubjt.edu.co/investigaciones-multidisciplinarias'),
    ('PLOS Computational Biology', 'Multidisciplinaria', 'Q1', 'Inglés', 4000.00, 4, 5, 'Revista dedicada a biología computacional y modelado biológico. doaj+1', 'https://journals.plos.org/ploscompbiol'),
    ('PLOS Genetics', 'Multidisciplinaria', 'Q1', 'Inglés', 5000.00, 5, 5, 'Revista centrada en genética y genómica.', 'https://journals.plos.org/plosgenetics'),
    ('PLOS Neglected Tropical Diseases', 'Multidisciplinaria', 'Q1', 'Inglés', 3700.00, 4, 4, 'Revista enfocada en salud global y enfermedades tropicales.', 'https://journals.plos.org/plosntds'),
    ('Frontiers in Genetics', 'Multidisciplinaria', 'Q1', 'Inglés', 3900.00, 4, 3, 'Revista de Frontiers especializada en genética. askbisht+2', 'https://www.frontiersin.org/journals/genetics'),
    ('Frontiers in Immunology', 'Multidisciplinaria', 'Q1', 'Inglés', 4200.00, 4, 4, 'Revista de inmunología de acceso abierto.', 'https://www.frontiersin.org/journals/immunology'),
    ('Frontiers in Microbiology', 'Multidisciplinaria', 'Q1', 'Inglés', 3900.00, 4, 5, 'Revista especializada en microbiología.', 'https://www.frontiersin.org/journals/microbiology'),
    ('Frontiers in Cell and Developmental Biology', 'Multidisciplinaria', 'Q1', 'Inglés', 4200.00, 4, 4, 'Revista de biología celular y del desarrollo.', 'https://www.frontiersin.org/journals/cell-dev-biol'),
    ('Frontiers in Molecular Neuroscience', 'Multidisciplinaria', 'Q1', 'Inglés', 4200.00, 4, 4, 'Revista especializada en neurociencia molecular.', 'https://www.frontiersin.org/journals/molecular-neuroscience'),
    ('Frontiers in Physiology', 'Multidisciplinaria', 'Q1', 'Inglés', 4000.00, 4, 4, 'Revista enfocada en fisiología.', 'https://www.frontiersin.org/journals/physiology'),
    ('Frontiers in Plant Science', 'Multidisciplinaria', 'Q1', 'Inglés', 4000.00, 4, 4, 'Revista de ciencias vegetales.', 'https://www.frontiersin.org/journals/plant-science'),
    ('Frontiers in Psychology', 'Multidisciplinaria', 'Q1', 'Inglés', 3700.00, 4, 3, 'Revista de psicología de acceso abierto.', 'https://www.frontiersin.org/journals/psychology'),
    ('Frontiers in Environmental Science', 'Multidisciplinaria', 'Q1', 'Inglés', 3900.00, 4, 4, 'Revista centrada en ciencias ambientales.', 'https://www.frontiersin.org/journals/environmental-science'),
    ('New England Journal of Medicine', 'Multidisciplinaria', 'Q1', 'Inglés', 0.00, 5, 5, 'Revista clínica de referencia internacional.', 'https://www.nejm.org/'),
    ('Nature', 'Multidisciplinaria', 'Q1', 'Inglés', 11500.00, 5, 5, 'Revista científica de referencia global.', 'https://www.nature.com/'),
    ('Science', 'Multidisciplinaria', 'Q1', 'Inglés', 0.00, 5, 5, 'Revista emblemática de la ciencia internacional.', 'https://www.science.org/'),
    ('Cell', 'Multidisciplinaria', 'Q1', 'Inglés', 0.00, 5, 4, 'Revista líder en biología celular y biomedicina.', 'https://www.cell.com/'),
    ('Proceedings of the National Academy of Sciences', 'Multidisciplinaria', 'Q1', 'Inglés', 0.00, 5, 5, 'Revista multidisciplinaria de gran prestigio.', 'https://www.pnas.org/'),
    ('Nature Reviews', 'Multidisciplinaria', 'Q1', 'Inglés', 0.00, 5, 5, 'Serie de revistas de revisión de alto impacto.', 'https://www.nature.com/nr'),
    ('Annual Review of', 'Multidisciplinaria', 'Q1', 'Inglés', 0.00, 5, 5, 'Serie editorial especializada en revisiones extensas.', 'https://www.annualreviews.org/'),
    ('Revista Mexicana de Investigación Educativa (RMIE)', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Revista líder en México sobre hallazgos empíricos del sistema educativo.', 'https://ojs.rmie.mx/index.php/rmie'),
    ('Revista Electrónica de Investigación Educativa (REDIE)', 'Educación', 'Q2', 'Español', 0.00, 4, 5, 'Publica artículos de investigación teórica y empírica vinculada a la práctica educativa.', 'https://redie.uabc.mx/redie'),
    ('Perfiles Educativos', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Una de las revistas más antiguas y prestigiosas de México en ciencias de la educación.', 'https://perfileseducativos.unam.mx/'),
    ('Computers & Education', 'Educación', 'Q1', 'Inglés', 3150.00, 5, 3, 'Revista de máximo impacto global en la integración de tecnologías digitales en la educación.', 'https://www.journals.elsevier.com/computers-and-education'),
    ('Educational Research Review', 'Educación', 'Q1', 'Inglés', 2950.00, 5, 3, 'Especializada exclusivamente en revisiones críticas de literatura educativa mundial.', 'https://www.journals.elsevier.com/educational-research-review'),
    ('Revista Iberoamericana de Educación Superior (RIES)', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Enfocada en el análisis de las políticas, gobierno y financiamiento de la educación superior.', 'https://www.ries.universia.unam.mx/'),
    ('Harvard Educational Review', 'Educación', 'Q1', 'Inglés', 2500.00, 5, 2, 'Revista de gran prestigio histórico que modela el debate sobre políticas públicas educativas.', 'https://www.harvardeducationalreview.org/'),
    ('Revista Complutense de Educación', 'Educación', 'Q2', 'Español', 0.00, 4, 5, 'Espacio de difusión para la investigación empírica en el ámbito escolar y pedagógico.', 'https://revistas.ucm.es/index.php/RCED'),
    ('Learning and Instruction', 'Educación', 'Q1', 'Inglés', 3200.00, 5, 3, 'Revista oficial de la European Association for Research on Learning and Instruction.', 'https://www.journals.elsevier.com/learning-and-instruction'),
    ('Educatio Siglo XXI', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Publicación abierta con monográficos dedicados a temáticas actuales de las aulas teóricas.', 'https://revistas.um.es/educatio'),
    ('American Educational Research Journal', 'Educación', 'Q1', 'Inglés', 3400.00, 5, 2, 'La revista insignia de la American Educational Research Association.', 'https://journals.sagepub.com/home/aer'),
    ('Revista de Educación', 'Educación', 'Q2', 'Español', 0.00, 4, 4, 'Revista oficial del estado español para la difusión de investigación en políticas públicas.', 'http://www.educacionyfp.gob.es/revista-de-educacion'),
    ('Review of Educational Research', 'Educación', 'Q1', 'Inglés', 3500.00, 5, 2, 'Frecuentemente rankeada como la #1 en impacto mundial dentro del área educativa.', 'https://journals.sagepub.com/home/rer'),
    ('Innovación Educativa', 'Educación', 'Q4', 'Español', 0.00, 2, 5, 'Dedicada a las nuevas metodologías de enseñanza, tecnologías y gestión institucional.', 'http://www.innovacion.ipn.mx/'),
    ('Educational Technology Research and Development', 'Educación', 'Q1', 'Inglés', 2850.00, 5, 2, 'Única revista centrada completamente en la investigación teórica del diseño instruccional.', 'https://www.springer.com/journal/11423'),
    ('Computers in the Schools', 'Educación', 'Q2', 'Inglés', 2600.00, 4, 2, 'Especializada en el uso práctico de herramientas digitales y computacionales en aulas de educación básica.', 'https://www.tandfonline.com/toc/wcis20/current'),
    ('Journal of Educational Psychology', 'Educación', 'Q1', 'Inglés', 3000.00, 5, 2, 'Líder global en procesos cognitivos, motivación y desarrollo psicológico escolar.', 'https://www.apa.org/pubs/journals/edu'),
    ('Apertura', 'Educación', 'Q4', 'Español', 0.00, 2, 5, 'Especializada en ambientes virtuales de aprendizaje y educación no convencional.', 'http://www.udgvirtual.udg.mx/apertura/'),
    ('British Journal of Educational Technology (BJET)', 'Educación', 'Q1', 'Inglés', 3100.00, 5, 2, 'Revista líder en Europa para la aplicación de TICs en sistemas educativos formales.', 'https://bera-journals.onlinelibrary.wiley.com/journal/14678535'),
    ('Revista Latinoamericana de Estudios Educativos', 'Educación', 'SIN ASIGNAR', 'Español', 0.00, 2, 5, 'Histórica revista dedicada a la equidad social, educación popular y exclusión.', 'https://rlee.ibero.mx/'),
    ('Teaching and Teacher Education', 'Educación', 'Q1', 'Inglés', 2700.00, 5, 2, 'Enfocada en el bienestar, desarrollo profesional y políticas de empleo para profesores.', 'https://www.journals.elsevier.com/teaching-and-teacher-education'),
    ('Revista Iberoamericana de Educación (RIE)', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Fomenta el intercambio de reformas estructurales educativas en toda Latinoamérica.', 'https://rieoei.org/'),
    ('Revista Iberoamericana de Tecnología en Educación y Educación en Tecnología (TE&ET)', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Enfocada en la integración de TICs en sistemas educativos y desarrollo de software para la enseñanza en la región iberoamericana.', 'https://teyet-revista.info.unlp.edu.ar/'),
    ('Sinéctica', 'Educación', 'Q4', 'Español', 0.00, 2, 5, 'Promueve una visión crítica y transformadora de la práctica de los educadores.', 'https://sinectica.iteso.mx/'),
    ('International Journal of Educational Technology in Higher Ed.', 'Educación', 'Q1', 'Inglés', 1950.00, 5, 2, 'Analiza el impacto disruptivo de la tecnología en el entorno universitario.', 'https://educationaltechnologyjournal.springeropen.com/'),
    ('Revista Interuniversitaria de Formación del Profesorado (RIFOP)', 'Educación', 'Q2', 'Español', 0.00, 4, 5, 'Centrada en la formación inicial, continua, desarrollo profesional y competencias del cuerpo docente.', 'https://recyt.fecyt.es/index.php/RIFOP'),
    ('RIDE Revista Iberoamericana para la Investigación Educativa', 'Educación', 'SIN ASIGNAR', 'Español', 0.00, 2, 5, 'Plataforma ágil enfocada a la publicación de docentes y alumnos de posgrado latinoamericanos.', 'https://www.ride.org.mx/index.php/RIDE'),
    ('Sociology of Education', 'Educación', 'Q1', 'Inglés', 3100.00, 5, 2, 'Analiza cómo interactúan las estructuras sociales con el rendimiento escolar.', 'https://journals.sagepub.com/home/soe'),
    ('Revista de Investigación Educativa (RIE-UM)', 'Educación', 'Q2', 'Español', 0.00, 4, 5, 'Revista de referencia institucional para métodos cuantitativos y cualitativos aplicados.', 'https://revistas.um.es/rie'),
    ('Journal of Research in Science Teaching', 'Educación', 'Q1', 'Inglés', 2900.00, 5, 2, 'La revista oficial de la National Association for Research in Science Teaching (NARST).', 'https://onlinelibrary.wiley.com/journal/10982736'),
    ('Alteridad', 'Educación', 'Q2', 'Español', 0.00, 4, 5, 'Foco interdisciplinar en filosofías de la educación y realidades sociales excluidas.', 'https://alteridad.ups.edu.ec/'),
    ('Early Childhood Research Quarterly', 'Educación', 'Q1', 'Inglés', 2600.00, 5, 2, 'Líder global en estudios empíricos sobre la infancia temprana y estimulación de 0 a 8 años.', 'https://www.journals.elsevier.com/early-childhood-research-quarterly'),
    ('Revista Latinoamericana de Investigación en Matemática Educativa', 'Educación', 'Q4', 'Español', 0.00, 2, 4, 'Revista especializada de nicho para la enseñanza de álgebra, cálculo y geometría.', 'http://www.relime.org/'),
    ('Higher Education', 'Educación', 'Q1', 'Inglés', 2800.00, 5, 2, 'Analiza sistemas universitarios públicos y privados desde un enfoque global comparativo.', 'https://www.springer.com/journal/10734'),
    ('Magis, Revista Internacional de Investigación en Educación', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Destaca por sus altos estándares de diseño editorial y solidez en metodologías mixtas.', 'https://revistas.javeriana.edu.co/index.php/MAGIS'),
    ('Curriculum Inquiry', 'Educación', 'Q2', 'Inglés', 2400.00, 4, 2, 'Dedicada al estudio profundo del diseño curricular, planes de estudio e ideologías en el aula.', 'https://www.tandfonline.com/toc/rcui20/current'),
    ('Revista Educación', 'Educación', 'Q4', 'Español', 0.00, 2, 5, 'Una de las revistas centroamericanas más estables y amigables con investigadores jóvenes.', 'https://revistas.ucr.ac.cr/index.php/educacion'),
    ('Journal of Learning Analytics', 'Educación', 'Q2', 'Inglés', 0.00, 4, 4, 'Enfocada en el uso de Big Data y minería de datos aplicada al seguimiento de alumnos.', 'https://learning-analytics.info/'),
    ('Ensaio: Avaliação e Políticas Públicas em Educação', 'Educación', 'Q2', 'Otro', 0.00, 4, 4, 'Especializada en métricas de evaluación del aprendizaje institucional y estatal.', 'https://www.scielo.br/j/ensaio/'),
    ('Qualitative Research in Education', 'Educación', 'Q2', 'Español', 0.00, 4, 5, 'Especializada en enfoques cualitativos puros: entrevistas, grupos focales e historias de vida.', 'https://hipatiapress.com/hpjournals/index.php/qre'),
    ('Revista Digital de Investigación en Docencia Universitaria', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Centrada en los retos didácticos y competencias del docente en el siglo XXI.', 'https://revistas.uned.ac.cr/index.php/innovaciones'),
    ('Educational Assessment', 'Educación', 'Q2', 'Inglés', 2550.00, 4, 2, 'Dedicada a las teorías psicométricas y desarrollo de exámenes estandarizados.', 'https://www.tandfonline.com/toc/HEDA20/current'),
    ('CPU-e, Revista de Investigación Educativa', 'Educación', 'SIN ASIGNAR', 'Español', 0.00, 2, 5, 'Espacio académico flexible que publica estados del arte y avances de tesis de posgrado.', 'https://cpue.uv.mx/index.php/cpue'),
    ('Journal of Digital Learning in Teacher Education', 'Educación', 'Q2', 'Inglés', 2450.00, 4, 2, 'Investiga modelos y estrategias para preparar a los futuros profesores en competencias y entornos digitales.', 'https://www.tandfonline.com/toc/ujdl20/current'),
    ('Revista de Educación a Distancia (RED)', 'Educación', 'Q1', 'Español', 0.00, 5, 5, 'Altamente citada en ambientes de aprendizaje híbrido, gamificación y MOOCs.', 'https://revistas.um.es/red'),
    ('International Journal of STEM Education', 'Educación', 'Q1', 'Inglés', 2190.00, 5, 2, 'Líder mundial en la investigación de la enseñanza integrada de Ciencias, Tecnología, Ingeniería y Matemáticas.', 'https://stemeducationjournal.springeropen.com/'),
    ('Studies in Higher Education', 'Educación', 'Q1', 'Inglés', 3300.00, 5, 2, 'Analiza de manera profunda la identidad del estudiante universitario y cambios institucionales.', 'https://www.tandfonline.com/toc/cshe20/current'),
    ('Revista Electrónica Educare', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Revista continua de acceso abierto absoluto, muy bien valorada por su amabilidad en dictamen.', 'https://www.revistas.una.ac.cr/index.php/educare'),
    ('Revista Latinoamericana de Tecnología Educativa (RELATEC)', 'Educación', 'Q3', 'Español', 0.00, 3, 5, 'Promueve la investigación y difusión abierta sobre software educativo, e-learning y alfabetización digital.', 'https://relatec.unex.es/'),
    ('Innovaciones Educativas', 'Educación', 'SIN ASIGNAR', 'Español', 0.00, 2, 5, 'Orientada a la difusión de experiencias directas en el aula para la mejora continua.', 'https://revistas.uned.ac.cr/index.php/innovaciones'),
    ('IEEE Transactions on Pattern Analysis and Machine Intelligence', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Revista líder en IA, visión por computadora y análisis de patrones', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=3468  '),
    ('IEEE Transactions on Neurall Networks', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Publica investigación en redes neuronales y aprendizaje profundo', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=23  '),
    ('IEEE Transactions on Software Engineering', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Enfoque en ingeniería de software, métodos y calidad', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=32  '),
    ('IEEE Transactions on Image Processing', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Cubre procesamiento, análisis y mejora de imágenes', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=83 '),
    ('IEEE Transactions on Mobile Computing', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Movilidad, redes inalámbricas y computación móvil', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=79 '),
    ('IEEE Transactions on Information Theory', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 2, 'Fundamentos teóricos de la información y codificación', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=18 '),
    ('IEEE Wireless Communications', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Tendencias y aplicaciones en comunicaciones inálambricas', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=79'),
    ('IEEE Transactions on Fuzzy Systems', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Sistemas difusos, control e inteligencia computacional', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=91'),
    ('IEEE Transactions on Industrial Electronics', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 3, 'Electrónica industrial, automatización y control', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=41'),
    ('IEEE Transactions  on Automatic Control', 'Tecnología', 'Q1', 'Inglés', 2300.00, 5, 2, 'Teoría y aplicaciones de control automático', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=9'),
    ('ACM Transactions on Software Engineering and Methodology', 'Tecnología', 'Q1', 'Inglés', 1800.00, 5, 3, 'Ingeniería en software, procesos y metodologías', 'http://tosem.acm.org/ '),
    ('ACM Transactions on Graphics', 'Tecnología', 'Q1', 'Inglés', 1800.00, 5, 3, 'Gráficos por computadora, visualización y animación', 'http://www.acm.org/tog/ '),
    ('ACM Computing Surveys', 'Tecnología', 'Q1', 'Inglés', 1800.00, 5, 4, 'Artículos de revisión exhaustivos en informática', 'https://dl.acm.org/journal/csur '),
    ('Journal of Machine Learning Research (JMLR)', 'Tecnología', 'Q1', 'Inglés', 0.00, 5, 4, 'Revista abierta especializada en aprendizaje automático', 'https://www.jmlr.org'),
    ('Artificial Intelligence', 'Tecnología', 'Q1', 'Inglés', 4050.00, 5, 3, 'Investigación teórica y aplicada en IA', 'https://www.sciencedirect.com/journal/artificial-intelligence '),
    ('Machine Learning', 'Tecnología', 'Q1', 'Inglés', 2990.00, 5, 3, 'Algoritmos y teoría de aprendizaje automático', 'https://www.springer.com/journal/10997'),
    ('Computational Liguistics', 'Tecnología', 'Q1', 'Inglés', 0.00, 5, 4, 'Procesamiento del lenguaje natural y lingüística computacional', 'https://cljournal.org'),
    ('International Journal of Computer Vision', 'Tecnología', 'Q1', 'Inglés', 2050.00, 5, 3, 'Visión por computadora y reconocimiento de patrones', 'https://www.editorialmanager.com/visi/default.aspx '),
    ('IEEE Pervasive Computing', 'Tecnología', 'Q1', 'Inglés', 2995.00, 4, 4, 'Computación ubicua, sensores y sistemas pervasivos', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6352'),
    ('IEEE Network', 'Tecnología', 'Q1', 'Inglés', 2800.00, 4, 3, 'Tecnologías, arquitecturas y gestión de redes', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=64'),
    ('Revista Cubana de Ciencias Infórmaticas', 'Tecnología', 'Q3', 'Español', 0.00, 4, 4, 'Publica investigaciones en informática, software y ciencias de la computación', 'http://scielo.sld.cu/revistas/rcci/eaboutj.htm'),
    ('Revista Peruana de Computación y Sistemas', 'Tecnología', 'Q4', 'Español', 0.00, 3, 4, 'Difunde trabajos en computación, sistemas e información aplicada', 'https://revistasinvestigacion.unmsm.edu.pe/index.php/rpcsis/index'),
    ('Ingenius. Revista de Ciencia y Tecnología', 'Tecnología', 'Q3', 'Español', 0.00, 4, 5, 'Revista multidisciplinaria con énfasis en ingeniería y tencología', 'https://ingenius.ups.edu.ec/ingenius/ '),
    ('Conciencia Tecnológica', 'Tecnología', 'Q3', 'Español', 0.00, 3, 4, 'Publica artículos sobre tecnología e ingeniería aplicada', 'https://www.latindex.org/latindex/ficha/4619 '),
    ('Revista de Tecnología', 'Tecnología', 'Q4', 'Español', 0.00, 3, 4, 'Revista academica de ingeniería y tecnología con enfoque regional ', 'https://www.tecnologia-ciencia-educacion.com/index.php/TCE '),
    ('TecnoLógicas', 'Tecnología', 'Q3', 'Español', 0.00, 2, 3, 'Revista orientada a ingeniería, innovación y desarrollo tecnologico', 'https://revistas.itm.edu.co/index.php/tecnologicas/index'),
    ('Ingeniería y Competitividad', 'Tecnología', 'Q4', 'Español', 0.00, 2, 3, 'Incluye investigaciones tecnologicas e ingenieriles con aplicación práctica', 'https://revistaingenieria.univalle.edu.co '),
    ('Revista Electrónica Gestión de las Personas y Tecnología', 'Tecnología', 'Q4', 'Español', 0.00, 4, 5, 'Trata gestión, innovación y tecnología en entornos organizacionales', 'https://doaj.org/toc/0718-5693 '),
    ('Revista Científica Ingeniería y Desarrollo', 'Tecnología', 'Q3', 'Español', 0.00, 4, 5, 'Publica resultados de investigación en ingeniería y desarrollo tecnologico', 'https://rcientificas.uninorte.edu.co/index.php/ingenieria '),
    ('Revista Iberoamericana de Tecnologías del Aprendizaje', 'Tecnología', 'Q2', 'Español', 0.00, 4, 5, 'Aborda tecnología educativa y uso de TIC en aprendizaje', 'https://vaep-rita.org/es/home-espanol/'),
    ('Pixel-Bit, Revista de Medios y Educación', 'Tecnología', 'Q3', 'Español', 0.00, 4, 5, 'Centrada en medios, educación y tecnología educativa', 'https://recyt.fecyt.es/index.php/pixel '),
    ('EDUTEC', 'Tecnología', 'Q3', 'Español', 0.00, 3, 5, 'Publica investigación sobre tecnología educativa y e-learning', 'https://www.edutec.es/revista/index.php/edutec-e '),
    ('RUSC', 'Tecnología', 'Q3', 'Español', 0.00, 2, 4, 'Tecnología educativa y sociedad del conocimiento', 'https://rusc.uoc.edu'),
    ('Revista Latinoamericana de Tecnología Educativa', 'Tecnología', 'Q4', 'Español', 0.00, 2, 3, 'Foca tecnología educativa y herramientas digitales ', 'https://relatec.unex.es'),
    ('Revista de Innovación Educativa y Tecnología', 'Tecnología', 'Q4', 'Español', 0.00, 2, 4, 'Difunde innovación didáctica con soporte tecnologico ', 'https://rpmie.org/revista-innovacion-educativa-tecnologia'),
    ('Revista de Tecnologías de la Información', 'Tecnología', 'Q4', 'Español', 0.00, 1, 3, 'Trata sistemas, TIC y soluciones informáticas', 'https://www.latindex.org/latindex/ficha/25800 '),
    ('Revista de Informática Educativa', 'Tecnología', 'Q4', 'Español', 0.00, 2, 3, 'Investigación sobre informatica aplicada a la educación', 'https://rieoei.org/rie/secciones'),
    ('Revista de Tecnología y Sociedad', 'Tecnología', 'Q4', 'Español', 0.00, 2, 3, 'Analiza impactos sociales y técnologicos de la innovación ', 'https://www.tecnologia-ciencia-educacion.com/index.php/TCE/inicio'),
    ('Revista de Sistemas y Tecnología', 'Tecnología', 'Q4', 'Español', 0.00, 1, 3, 'Publica estudios sobre sistemas de información y tecnología', 'https://revistas.unsa.edu.pe/index.php/rsit'),
    ('Revista de Ingeniería e Innovación Tecnológica', 'Tecnología', 'Q4', 'Español', 0.00, 2, 3, 'Investigación aplicada en ingeniería e innovación', 'https://revistas.uss.edu.pe/index.php/ING '),
    ('Revista Tecnología en Marcha', 'Tecnología', 'Q2', 'Español', 0.00, 4, 4, 'Publica investigación en ingeniería, tecnología y áreas aplicadas', 'https://revistas.tec.ac.cr/index.php/tec_marcha'),
    ('ReCIBE, Revista electrónica de Computación, Informática, Biomédica y Electrónica', 'Tecnología', 'Q2', 'Español', 0.00, 4, 5, 'Difunde estudios y desarrollos tecnológicos de corte científico-investigativo', 'https://recibe.cucei.udg.mx '),
    ('Ciencia, Tecnología y Salud', 'Tecnología', 'Q2', 'Español', 0.00, 3, 4, 'Revista académica arbitrada sobre áreas científicas, tecnológicas y de salud', 'https://revistas.usac.edu.gt/index.php/cytes '),
    ('Revista Iberoamericana de Tecnología en Educación y Educación en Tecnología', 'Tecnología', 'Q2', 'Español', 0.00, 5, 5, 'Publica resultados en tecnología educativa y eduación en tecnología', 'https://teyet-revista.info.unlp.edu.ar'),
    ('Eductec, Revista Electrónica de Tecnología Educativa', 'Tecnología', 'Q2', 'Español', 0.00, 4, 5, 'Centrada en investigación sobre tecnología educativa e innovación docente', 'https://www.edutec.es/revista/index.php/edutec-e '),
    ('ICONO 14', 'Tecnología', 'Q2', 'Español', 0.00, 4, 4, 'Revista científica de comunicación, sociedad digital y tecnología.', 'https://icono14.net '),
    ('Publicaciones en Ciencias Y tecnología', 'Tecnología', 'Q2', 'Español', 0.00, 3, 4, 'Publica estudios cientificos y tecnológicos de carácter multidisciplinario', 'https://revistas.uclave.org/index.php/pcyt '),
    ('Revista de Tecnología y Ciencia', 'Tecnología', 'Q2', 'Español', 0.00, 3, 4, 'Enfocada en resultados de investigación aplicada en tecnología', 'https://rtyc.utn.edu.ar/index.php/rtyc '),
    ('Revista Digital de Tecnologías Aplicadas', 'Tecnología', 'Q2', 'Español', 0.00, 3, 4, 'Difunde investigaciones sobre aplicaciones tecnológicas y sistemas difitales', 'https://rtyc.utn.edu.ar/index.php/rtyc '),
    ('Revista Iberoamericana de Sistemas, Cibernetica e Informatica', 'Tecnología', 'Q2', 'Español', 0.00, 4, 4, 'Aborda sistemas informática, control y tecnologías afines', 'https://www.iiisci.org/journal/risci ');

-- --------------------------------------------
-- 3. Relación revista <-> indexación
-- --------------------------------------------
INSERT INTO revista_indexacion (id_revista, id_indexacion) VALUES
    (1, 33),
    (1, 26),
    (1, 34),
    (1, 30),
    (1, 17),
    (1, 8),
    (1, 11),
    (1, 18),
    (2, 33),
    (2, 26),
    (2, 30),
    (2, 17),
    (2, 8),
    (2, 21),
    (3, 33),
    (3, 26),
    (3, 30),
    (3, 17),
    (3, 34),
    (3, 8),
    (3, 21),
    (4, 33),
    (4, 26),
    (4, 30),
    (4, 17),
    (4, 16),
    (5, 33),
    (5, 26),
    (5, 34),
    (5, 30),
    (5, 17),
    (5, 8),
    (5, 18),
    (6, 33),
    (6, 26),
    (6, 30),
    (6, 17),
    (6, 21),
    (7, 17),
    (7, 31),
    (7, 8),
    (7, 15),
    (7, 21),
    (8, 17),
    (8, 30),
    (8, 21),
    (8, 15),
    (9, 17),
    (9, 8),
    (9, 30),
    (10, 17),
    (10, 30),
    (10, 8),
    (10, 21),
    (11, 17),
    (11, 30),
    (11, 13),
    (11, 21),
    (12, 17),
    (12, 8),
    (12, 31),
    (13, 33),
    (13, 26),
    (13, 34),
    (13, 30),
    (13, 17),
    (13, 8),
    (13, 18),
    (13, 11),
    (14, 33),
    (14, 26),
    (14, 34),
    (14, 30),
    (14, 17),
    (14, 8),
    (14, 11),
    (14, 18),
    (15, 33),
    (15, 26),
    (15, 34),
    (15, 30),
    (15, 17),
    (15, 8),
    (16, 33),
    (16, 26),
    (16, 34),
    (16, 30),
    (16, 17),
    (17, 33),
    (17, 26),
    (17, 30),
    (17, 17),
    (17, 8),
    (17, 18),
    (17, 11),
    (18, 33),
    (18, 8),
    (18, 17),
    (18, 30),
    (18, 9),
    (18, 20),
    (18, 18),
    (19, 33),
    (19, 30),
    (19, 17),
    (19, 8),
    (19, 1),
    (19, 18),
    (20, 33),
    (20, 34),
    (20, 30),
    (20, 17),
    (20, 8),
    (20, 1),
    (21, 33),
    (21, 26),
    (21, 34),
    (21, 30),
    (21, 8),
    (21, 18),
    (21, 25),
    (22, 17),
    (22, 30),
    (22, 8),
    (22, 18),
    (22, 15),
    (23, 33),
    (23, 30),
    (23, 17),
    (23, 8),
    (23, 18),
    (24, 33),
    (24, 26),
    (24, 30),
    (24, 17),
    (25, 33),
    (25, 26),
    (25, 34),
    (25, 30),
    (25, 17),
    (26, 33),
    (26, 26),
    (26, 34),
    (26, 11),
    (26, 6),
    (27, 33),
    (27, 26),
    (27, 34),
    (27, 11),
    (27, 6),
    (28, 33),
    (28, 26),
    (28, 34),
    (28, 11),
    (29, 33),
    (29, 26),
    (29, 34),
    (29, 11),
    (30, 33),
    (30, 26),
    (30, 34),
    (30, 8),
    (30, 11),
    (30, 25),
    (31, 33),
    (31, 26),
    (31, 34),
    (31, 8),
    (31, 25),
    (32, 33),
    (32, 26),
    (32, 34),
    (32, 8),
    (32, 25),
    (32, 11),
    (33, 33),
    (33, 26),
    (33, 34),
    (33, 8),
    (33, 25),
    (33, 11),
    (34, 33),
    (34, 26),
    (34, 34),
    (34, 8),
    (34, 25),
    (35, 33),
    (35, 26),
    (35, 34),
    (35, 8),
    (36, 33),
    (36, 26),
    (36, 34),
    (36, 8),
    (36, 11),
    (36, 25),
    (37, 33),
    (37, 26),
    (37, 34),
    (37, 8),
    (37, 25),
    (38, 33),
    (38, 26),
    (38, 34),
    (38, 8),
    (38, 25),
    (39, 33),
    (39, 26),
    (39, 34),
    (39, 8),
    (39, 25),
    (40, 33),
    (40, 26),
    (40, 34),
    (40, 8),
    (40, 25),
    (41, 33),
    (41, 34),
    (41, 8),
    (41, 23),
    (42, 33),
    (42, 26),
    (42, 34),
    (42, 11),
    (43, 33),
    (43, 26),
    (43, 34),
    (43, 11),
    (44, 33),
    (44, 26),
    (44, 34),
    (44, 11),
    (45, 33),
    (45, 26),
    (45, 34),
    (45, 8),
    (46, 33),
    (46, 26),
    (46, 34),
    (46, 11),
    (47, 33),
    (47, 26),
    (47, 34),
    (47, 11),
    (48, 33),
    (48, 26),
    (48, 34),
    (48, 30),
    (48, 17),
    (49, 33),
    (49, 26),
    (49, 34),
    (49, 30),
    (49, 17),
    (50, 33),
    (50, 26),
    (50, 34),
    (50, 30),
    (50, 17),
    (51, 33),
    (51, 26),
    (51, 34),
    (51, 8),
    (52, 28),
    (52, 33),
    (52, 25),
    (52, 8),
    (52, 14),
    (53, 28),
    (53, 33),
    (53, 24),
    (53, 8),
    (53, 14),
    (54, 28),
    (54, 33),
    (54, 8),
    (54, 14),
    (55, 14),
    (56, 24),
    (56, 19),
    (56, 34),
    (56, 33),
    (56, 8),
    (57, 33),
    (57, 26),
    (57, 34),
    (58, 33),
    (58, 8),
    (58, 25),
    (58, 24),
    (58, 19),
    (58, 34),
    (59, 28),
    (59, 33),
    (59, 24),
    (59, 25),
    (59, 8),
    (60, 12),
    (60, 33),
    (60, 8),
    (60, 14),
    (61, 17),
    (62, 17),
    (63, 17),
    (64, 17),
    (65, 28),
    (65, 33),
    (65, 24),
    (65, 8),
    (66, 28),
    (66, 33),
    (66, 24),
    (66, 8),
    (67, 28),
    (67, 33),
    (67, 24),
    (67, 8),
    (68, 28),
    (68, 33),
    (68, 8),
    (69, 28),
    (69, 33),
    (69, 24),
    (69, 8),
    (70, 28),
    (70, 33),
    (70, 24),
    (70, 8),
    (71, 28),
    (71, 33),
    (71, 24),
    (71, 8),
    (72, 28),
    (72, 33),
    (72, 24),
    (72, 8),
    (73, 28),
    (73, 33),
    (73, 24),
    (73, 8),
    (74, 28),
    (74, 33),
    (74, 24),
    (74, 8),
    (75, 28),
    (75, 33),
    (75, 24),
    (75, 8),
    (76, 28),
    (76, 33),
    (76, 24),
    (76, 8),
    (77, 28),
    (77, 33),
    (77, 24),
    (77, 19),
    (77, 11),
    (78, 28),
    (78, 33),
    (78, 24),
    (78, 19),
    (78, 11),
    (79, 28),
    (79, 33),
    (79, 24),
    (79, 19),
    (80, 28),
    (80, 33),
    (80, 24),
    (80, 19),
    (81, 28),
    (81, 33),
    (81, 24),
    (81, 19),
    (82, 28),
    (82, 33),
    (82, 24),
    (82, 19),
    (83, 28),
    (83, 33),
    (83, 24),
    (84, 33),
    (84, 30),
    (84, 17),
    (84, 27),
    (85, 33),
    (85, 12),
    (85, 30),
    (85, 27),
    (86, 33),
    (86, 30),
    (86, 17),
    (86, 27),
    (87, 33),
    (87, 34),
    (87, 32),
    (88, 33),
    (88, 34),
    (89, 33),
    (89, 17),
    (89, 27),
    (90, 33),
    (90, 34),
    (91, 33),
    (91, 12),
    (91, 17),
    (92, 33),
    (92, 34),
    (93, 33),
    (93, 12),
    (93, 9),
    (94, 33),
    (94, 34),
    (95, 33),
    (95, 34),
    (95, 17),
    (96, 33),
    (96, 34),
    (97, 33),
    (97, 17),
    (97, 7),
    (98, 33),
    (98, 34),
    (99, 33),
    (99, 12),
    (100, 33),
    (100, 34),
    (101, 33),
    (101, 27),
    (101, 17),
    (102, 33),
    (102, 34),
    (103, 17),
    (103, 27),
    (103, 30),
    (104, 33),
    (104, 34),
    (105, 33),
    (105, 17),
    (105, 9),
    (106, 33),
    (106, 30),
    (106, 17),
    (107, 33),
    (107, 12),
    (107, 30),
    (108, 33),
    (108, 34),
    (109, 33),
    (109, 12),
    (109, 9),
    (110, 17),
    (110, 9),
    (110, 7),
    (111, 33),
    (111, 34),
    (112, 33),
    (112, 12),
    (112, 17),
    (113, 33),
    (113, 34),
    (114, 33),
    (114, 12),
    (114, 17),
    (115, 33),
    (115, 34),
    (116, 33),
    (116, 12),
    (116, 30),
    (117, 33),
    (117, 34),
    (118, 33),
    (118, 12),
    (118, 27),
    (119, 33),
    (119, 34),
    (120, 33),
    (120, 12),
    (120, 17),
    (121, 33),
    (121, 12),
    (122, 33),
    (122, 34),
    (122, 30),
    (123, 33),
    (123, 12),
    (123, 9),
    (124, 33),
    (124, 12),
    (124, 17),
    (125, 33),
    (125, 12),
    (126, 17),
    (126, 27),
    (126, 7),
    (127, 33),
    (127, 12),
    (128, 33),
    (128, 12),
    (128, 9),
    (129, 33),
    (129, 34),
    (130, 33),
    (130, 34),
    (131, 33),
    (131, 12),
    (131, 30),
    (132, 33),
    (132, 9),
    (132, 17),
    (133, 17),
    (133, 9),
    (133, 8),
    (134, 33),
    (134, 34),
    (134, 29),
    (135, 33),
    (135, 34),
    (135, 29),
    (136, 33),
    (136, 34),
    (136, 29),
    (137, 33),
    (137, 34),
    (137, 29),
    (138, 33),
    (138, 34),
    (138, 29),
    (139, 33),
    (139, 34),
    (139, 29),
    (140, 33),
    (140, 34),
    (140, 29),
    (141, 33),
    (141, 34),
    (141, 29),
    (142, 33),
    (142, 34),
    (142, 29),
    (143, 33),
    (143, 34),
    (143, 29),
    (144, 33),
    (144, 34),
    (144, 29),
    (145, 33),
    (145, 34),
    (145, 29),
    (146, 33),
    (146, 34),
    (146, 29),
    (147, 33),
    (147, 34),
    (147, 29),
    (148, 33),
    (148, 34),
    (148, 29),
    (149, 33),
    (149, 34),
    (149, 29),
    (150, 33),
    (150, 34),
    (150, 29),
    (151, 33),
    (151, 34),
    (151, 29),
    (152, 33),
    (152, 34),
    (152, 29),
    (153, 33),
    (153, 34),
    (153, 29),
    (154, 17),
    (154, 27),
    (155, 4),
    (156, 27),
    (156, 4),
    (157, 27),
    (157, 4),
    (158, 9),
    (158, 4),
    (159, 27),
    (159, 17),
    (160, 27),
    (160, 17),
    (161, 27),
    (161, 17),
    (162, 5),
    (163, 2),
    (164, 2),
    (165, 2),
    (166, 33),
    (166, 4),
    (167, 17),
    (167, 4),
    (168, 17),
    (168, 4),
    (169, 3),
    (170, 4),
    (171, 17),
    (172, 3),
    (173, 4),
    (174, 17),
    (174, 22),
    (175, 3),
    (176, 22),
    (178, 2),
    (179, 9),
    (179, 4),
    (180, 22),
    (181, 10),
    (182, 2),
    (183, 10);