CREATE TABLE IF NOT EXISTS revistas (
    id                      INT AUTO_INCREMENT PRIMARY KEY,
    nombre                  VARCHAR(300) NOT NULL,
    area                    VARCHAR(200) DEFAULT NULL,
    pais                    VARCHAR(100) DEFAULT NULL,
    cuartil_sjr             ENUM('Q1','Q2','Q3','Q4','S/D') DEFAULT 'S/D',
    apc_tipo                ENUM('gratuita','pago','hibrida') DEFAULT 'gratuita',
    apc_descripcion         VARCHAR(250) DEFAULT NULL,
    indexaciones            VARCHAR(300) DEFAULT NULL,
    editorial               VARCHAR(200) DEFAULT NULL,
    idiomas                 VARCHAR(150) DEFAULT NULL,
    tipos_articulos         VARCHAR(300) DEFAULT NULL,
    acceso                  ENUM('abierto','suscripcion','hibrido') DEFAULT 'abierto',
    confiabilidad           TINYINT UNSIGNED DEFAULT NULL,
    recomendada_estudiantes TINYINT UNSIGNED DEFAULT NULL,
    descripcion             TEXT DEFAULT NULL,
    sitio_web               VARCHAR(500) DEFAULT NULL,
    fecha_registro          DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO revistas (nombre, area, pais, cuartil_sjr, apc_tipo, apc_descripcion, indexaciones, editorial, idiomas, tipos_articulos, acceso, confiabilidad, recomendada_estudiantes, descripcion, sitio_web) VALUES
('Salud Publica de Mexico', 'Salud publica / epidemiologia', 'Mexico', 'Q2', 'gratuita', '$0, acceso abierto financiado por el INSP', 'Scopus, PubMed/MEDLINE, Web of Science, SciELO, Latindex, DOAJ, EMBASE, Lilacs', 'Instituto Nacional de Salud Publica (INSP)', 'Espanol, Ingles', 'Originales, revisiones, editoriales, cartas al editor, casos clinicos', 'abierto', 5, 3, 'Una de las revistas de salud publica mas importantes de Mexico y Latinoamerica. Fundada en 1959. Arbitraje doble ciego.', 'https://saludpublica.mx'),
('Boletin Medico del Hospital Infantil de Mexico', 'Pediatria / medicina infantil', 'Mexico', 'Q3', 'gratuita', '$0, acceso abierto', 'Scopus, PubMed/MEDLINE, SciELO, Latindex, DOAJ, Medigraphic', 'Hospital Infantil de Mexico Federico Gomez / Elsevier', 'Espanol, Ingles', 'Investigacion original, casos clinicos, revisiones, cartas al editor', 'abierto', 5, 5, 'Publicacion oficial del Hospital Infantil de Mexico Federico Gomez. Una de las revistas medicas mas antiguas del pais. Fundada en 1944.', 'https://www.bmhim.com'),
('Salud Mental', 'Psiquiatria / salud mental / neurociencias', 'Mexico', 'Q3', 'gratuita', '$0, acceso abierto', 'Scopus, PubMed/MEDLINE, Web of Science, SciELO, Latindex, DOAJ, Lilacs', 'Instituto Nacional de Psiquiatria Ramon de la Fuente Muniz', 'Espanol, Ingles', 'Investigacion original, revision sistematica, casos clinicos, metaanalisis', 'abierto', 5, 3, 'Unica revista mexicana de psiquiatria indexada en Web of Science y Scopus.', 'https://www.revistasaludmental.mx'),
('Revista Panamericana de Salud Publica (OPS/PAHO)', 'Salud publica / salud global', 'Internacional', 'Q2', 'gratuita', '$0, financiada por la OPS/OMS', 'Scopus, PubMed/MEDLINE, Web of Science, SciELO, Latindex, DOAJ, Lilacs, EMBASE', 'Organizacion Panamericana de la Salud (OPS / OMS)', 'Espanol, Ingles, Portugues, Frances', 'Originales, revision sistematica, metaanalisis, politica de salud, cartas', 'abierto', 5, 3, 'La publicacion cientifica mas importante de la OPS. Referente en salud publica latinoamericana.', 'https://journal.paho.org/es'),
('Cadernos de Saude Publica (Brasil)', 'Salud publica / epidemiologia / ciencias sociales en salud', 'Brasil', 'Q1', 'gratuita', '$0, acceso abierto total', 'Scopus, PubMed/MEDLINE, Web of Science, SciELO, Latindex, DOAJ, EMBASE, Lilacs', 'Escola Nacional de Saude Publica Sergio Arouca (FIOCRUZ)', 'Portugues, Espanol, Ingles', 'Originales, revision, notas de investigacion, debate, cartas', 'abierto', 5, 3, 'Una de las revistas de salud publica mas citadas de Latinoamerica. Q1 en Scopus. Publicada por FIOCRUZ.', 'https://www.scielo.br/csp'),
('Biomedica (Colombia)', 'Biomedicina / enfermedades infecciosas / salud publica', 'Colombia', 'Q3', 'gratuita', '$0, acceso abierto', 'Scopus, PubMed/MEDLINE, SciELO, Latindex, DOAJ, Lilacs, EMBASE', 'Instituto Nacional de Salud de Colombia', 'Espanol, Ingles', 'Originales, revision, comunicaciones breves, cartas, casos clinicos', 'abierto', 5, 5, 'Publicacion oficial del Instituto Nacional de Salud de Colombia. Enfasis en enfermedades tropicales y virologia.', 'https://revistabiomedica.org'),
('Ciencia & Enfermeria', 'Enfermeria / ciencias de la salud', 'Chile', 'Q3', 'gratuita', '$0', 'Scopus, Web of Science, SciELO, Latindex, DOAJ, CINAHL', 'Universidad de Concepcion, Chile', 'Espanol, Ingles', 'Originales, revisiones, educacion en enfermeria, casos clinicos', 'abierto', 5, 5, 'Primera revista de enfermeria chilena en ingresar a Web of Science y Scopus. Referente regional para la disciplina.', 'https://www.scielo.cl/scielo.php?pid=0717-9553&script=sci_serial'),
('Journal of Global Health', 'Salud global / salud internacional', 'Internacional', 'Q1', 'gratuita', '$0, acceso abierto sin APC', 'Scopus, PubMed/MEDLINE, Web of Science, DOAJ, PMC', 'International Society of Global Health (ISGH)', 'Ingles', 'Originales, revision sistematica, metaanalisis, comentarios', 'abierto', 5, 3, 'Revista Q1 sin APC. Excelente para investigacion sobre desigualdades globales en salud y salud materno-infantil.', 'https://jogh.org'),
('International Journal of Clinical and Health Psychology', 'Psicologia clinica / salud mental', 'Espana', 'Q1', 'gratuita', '$0, acceso abierto total sin APC', 'Scopus, Web of Science, DOAJ, PsycINFO', 'Asociacion Espanola de Psicologia Conductual (AEPC) / Elsevier', 'Ingles, Espanol, Portugues', 'Originales, revision sistematica, metaanalisis, estudios de caso', 'abierto', 5, 5, 'Q1 en Scopus y WoS sin ningun APC. Acepta en espanol. Ideal para investigacion en psicologia de la salud hispanohablante.', 'https://www.ijchp.net'),
('Gaceta Sanitaria', 'Salud publica / epidemiologia / politica de salud', 'Espana', 'Q2', 'gratuita', '$0, acceso abierto', 'Scopus, PubMed/MEDLINE, Web of Science, SciELO, Latindex', 'Sociedad Espanola de Epidemiologia (SEE) / Elsevier', 'Espanol, Ingles', 'Originales, revision, notas, cartas, editoriales, casos', 'abierto', 5, 5, 'Revista Q2 en espanol sin APC, indexada en PubMed y WoS. Muy recomendada para investigadores de Latinoamerica.', 'https://www.gacetasanitaria.org');
